### ISSUE TITLE
Errors in Windows Built versions of RItools

### ISSUE THREAD

**Issue by jwbowers** [markmfredrickson/RItools#71]
from Uwe Ligges 

> Thanks, we see that this gives some (minor?) diffs under 32-bit Windows and crashes under 64-bit Windows using the new gcc-4.9.3 based toolchain for Winodws:

```
 Running 'xBalanceTests.R' [3s]
 Comparing 'xBalanceTests.Rout' to 'xBalanceTests.Rout.save' ...21,28c21,28
< date          -0.1098 -0.3052
< t1             0.0976  0.2830
< t2             0.9861  2.4674
< cap            0.3525  0.8948
< ne            -0.1656 -0.4334
< ct            -0.3113 -0.8121
< bw             0.0445  0.1202
< cum.n         -0.1005 -0.2598
---
> date          -0.1107 -0.3052
> t1             0.0982  0.2830
> t2             0.9941  2.4674
> cap            0.3568  0.8948
> ne            -0.1675 -0.4334
> ct            -0.3147 -0.8121
> bw             0.0450  0.1202
> cum.n         -0.1017 -0.2598
35,42c35,42
< date           68.5000  68.6182  -0.1182  -0.1098  -0.3052
< t1             14.0000  13.6364   0.3636   0.0976   0.2830
< t2             69.1000  59.3182   9.7818   0.9861   2.4674
< cap           869.8000 805.1818  64.6182   0.3525   0.8948
< ne              0.2000   0.2727  -0.0727  -0.1656  -0.4334
< ct              0.3000   0.4545  -0.1545  -0.3113  -0.8121
< bw              0.2000   0.1818   0.0182   0.0445   0.1202
< cum.n           8.1000   8.7273  -0.6273  -0.1005  -0.2598
---
> date           68.5000  68.6182  -0.1182  -0.1107  -0.3052
> t1             14.0000  13.6364   0.3636   0.0982   0.2830
> t2             69.1000  59.3182   9.7818   0.9941   2.4674
> cap           869.8000 805.1818  64.6182   0.3568   0.8948
> ne              0.2000   0.2727  -0.0727  -0.1675  -0.4334
> ct              0.3000   0.4545  -0.1545  -0.3147  -0.8121
> bw              0.2000   0.1818   0.0182   0.0450   0.1202
> cum.n           8.1000   8.7273  -0.6273  -0.1017  -0.2598
53,60c53,60
< date           68.5000  68.3905   0.1095   0.1001   0.2923   68.5000 68.6182  -0.1182  -0.1098  -0.3052
< t1             14.0000  13.2000   0.8000   0.2154   0.7918   14.0000 13.6364   0.3636   0.0976   0.2830
< t2             69.1000  59.0684  10.0316   1.0226   2.3094   69.1000 59.3182   9.7818   0.9861   2.4674
< cap           869.8000 807.4842  62.3158   0.3587   0.9188  869.8000 805.1818  64.6182   0.3525   0.8948
< ne              0.2000   0.2211  -0.0211  -0.0497  -0.1445    0.2000 0.2727  -0.0727  -0.1656  -0.4334
< ct              0.3000   0.4316  -0.1316  -0.2657  -0.5828    0.3000 0.4545  -0.1545  -0.3113  -0.8121
< bw              0.2000   0.2105  -0.0105  -0.0251  -0.3088    0.2000 0.1818   0.0182   0.0445   0.1202
< cum.n           8.1000   8.7158  -0.6158  -0.1041  -0.3397    8.1000 8.7273  -0.6273  -0.1005  -0.2598
---
> date           68.5000  68.7197  -0.2197  -0.2087   0.2923   68.5000 68.6182  -0.1182  -0.1107  -0.3052
> t1             14.0000  13.8310   0.1690   0.0457   0.7918   14.0000 13.6364   0.3636   0.0982   0.2830
> t2             69.1000  59.4296   9.6704   0.9777   2.3094   69.1000 59.3182   9.7818   0.9941   2.4674
> cap           869.8000 804.1549  65.6451   0.3544   0.9188  869.8000 805.1818  64.6182   0.3568   0.8948
> ne              0.2000   0.2958  -0.0958  -0.2176  -0.1445    0.2000  0.2727  -0.0727  -0.1675  -0.4334
> ct              0.3000   0.4648  -0.1648  -0.3350  -0.5828    0.3000  0.4545  -0.1545  -0.3147  -0.8121
> bw              0.2000   0.1690   0.0310   0.0776  -0.3088    0.2000  0.1818   0.0182   0.0450   0.1202
> cum.n           8.1000   8.7324  -0.6324  -0.1003  -0.3397    8.1000  8.7273  -0.6273  -0.1017  -0.2598
73,80c73,80
< date           68.5000  68.3905   0.1095   0.1001   0.2923   68.5000 68.6182  -0.1182  -0.1098  -0.3052
< t1             14.0000  13.2000   0.8000   0.2154   0.7918   14.0000 13.6364   0.3636   0.0976   0.2830
< t2             69.1000  59.0684  10.0316   1.0226   2.3094   69.1000 59.3182   9.7818   0.9861   2.4674
< cap           869.8000 807.4842  62.3158   0.3587   0.9188  869.8000 805.1818  64.6182   0.3525   0.8948
< ne              0.2000   0.2211  -0.0211  -0.0497  -0.1445    0.2000 0.2727  -0.0727  -0.1656  -0.4334
< ct              0.3000   0.4316  -0.1316  -0.2657  -0.5828    0.3000 0.4545  -0.1545  -0.3113  -0.8121
< bw              0.2000   0.2105  -0.0105  -0.0251  -0.3088    0.2000 0.1818   0.0182   0.0445   0.1202
< cum.n           8.1000   8.7158  -0.6158  -0.1041  -0.3397    8.1000 8.7273  -0.6273  -0.1005  -0.2598
---
> date           68.5000  68.7197  -0.2197  -0.2087   0.2923   68.5000 68.6182  -0.1182  -0.1107  -0.3052
> t1             14.0000  13.8310   0.1690   0.0457   0.7918   14.0000 13.6364   0.3636   0.0982   0.2830
> t2             69.1000  59.4296   9.6704   0.9777   2.3094   69.1000 59.3182   9.7818   0.9941   2.4674
> cap           869.8000 804.1549  65.6451   0.3544   0.9188  869.8000 805.1818  64.6182   0.3568   0.8948
> ne              0.2000   0.2958  -0.0958  -0.2176  -0.1445    0.2000  0.2727  -0.0727  -0.1675  -0.4334
> ct              0.3000   0.4648  -0.1648  -0.3350  -0.5828    0.3000  0.4545  -0.1545  -0.3147  -0.8121
> bw              0.2000   0.1690   0.0310   0.0776  -0.3088    0.2000  0.1818   0.0182   0.0450   0.1202
> cum.n           8.1000   8.7324  -0.6324  -0.1003  -0.3397    8.1000  8.7273  -0.6273  -0.1017  -0.2598
95,102c95,102
< date           68.5000  68.3905   0.1095   0.1001   0.2923   68.5000 68.6182  -0.1182  -0.1098  -0.3052
< t1             14.0000  13.2000   0.8000   0.2154   0.7918   14.0000 13.6364   0.3636   0.0976   0.2830
< t2             69.1000  59.0684  10.0316   1.0226   2.3094   69.1000 59.3182   9.7818   0.9861   2.4674
< cap           869.8000 807.4842  62.3158   0.3587   0.9188  869.8000 805.1818  64.6182   0.3525   0.8948
< ne              0.2000   0.2211  -0.0211  -0.0497  -0.1445    0.2000 0.2727  -0.0727  -0.1656  -0.4334
< ct              0.3000   0.4316  -0.1316  -0.2657  -0.5828    0.3000 0.4545  -0.1545  -0.3113  -0.8121
< bw              0.2000   0.2105  -0.0105  -0.0251  -0.3088    0.2000 0.1818   0.0182   0.0445   0.1202
< cum.n           8.1000   8.7158  -0.6158  -0.1041  -0.3397    8.1000 8.7273  -0.6273  -0.1005  -0.2598
---
> date           68.5000  68.7197  -0.2197  -0.2087   0.2923   68.5000 68.6182  -0.1182  -0.1107  -0.3052
> t1             14.0000  13.8310   0.1690   0.0457   0.7918   14.0000 13.6364   0.3636   0.0982   0.2830
> t2             69.1000  59.4296   9.6704   0.9777   2.3094   69.1000 59.3182   9.7818   0.9941   2.4674
> cap           869.8000 804.1549  65.6451   0.3544   0.9188  869.8000 805.1818  64.6182   0.3568   0.8948
> ne              0.2000   0.2958  -0.0958  -0.2176  -0.1445    0.2000  0.2727  -0.0727  -0.1675  -0.4334
> ct              0.3000   0.4648  -0.1648  -0.3350  -0.5828    0.3000  0.4545  -0.1545  -0.3147  -0.8121
> bw              0.2000   0.1690   0.0310   0.0776  -0.3088    0.2000  0.1818   0.0182   0.0450   0.1202
> cum.n           8.1000   8.7324  -0.6324  -0.1003  -0.3397    8.1000  8.7273  -0.6273  -0.1017  -0.2598
147,156c147,156
< date                  0.0203  0.0372
< t1                    0.0976  0.2830
< t2                    0.9861  2.4674
< cap                   0.3525  0.8948
< ne                   -0.1656 -0.4334
< ct                   -0.3113 -0.8121
< bw                    0.0445  0.1202
< cum.n                -0.1005 -0.2598
< date.NAFALSE          1.2613  2.5308
< date.NATRUE          -1.2613 -2.5308
---
> date                  0.0204  0.0372
> t1                    0.0982  0.2830
> t2                    0.9941  2.4674
> cap                   0.3568  0.8948
> ne                   -0.1675 -0.4334
> ct                   -0.3147 -0.8121
> bw                    0.0450  0.1202
> cum.n                -0.1017 -0.2598
> date.NAFALSE          1.2881  2.5308
> date.NATRUE          -1.2881 -2.5308
181,204c181,204
< date              0.1001  0.2923  -0.1098 -0.3052
< t1                0.2154  0.7918   0.0976  0.2830
< t2                1.0226  2.3094   0.9861  2.4674
< cap               0.3587  0.9188   0.3525  0.8948
< ne               -0.0497 -0.1445  -0.1656 -0.4334
< ct               -0.2657 -0.5828  -0.3113 -0.8121
< bw               -0.0251 -0.3088   0.0445  0.1202
< cum.nF1          -0.0330 -0.0924  -0.1088 -0.2838
< cum.nF2           0.0899  0.2610   0.0298  0.0805
< cum.nF3          -0.0330 -0.0924  -0.1088 -0.2838
< cum.nF5           0.2412  0.7509   0.2023  0.5815
< cum.nF6          -0.2702 -0.6070  -0.3015 -0.6742
< cum.nF7          -0.5501 -1.1509  -0.4369 -0.9692
< cum.nF8           0.2711  0.9460   0.4626  1.3683
< cum.nF11          0.2711  0.7454   0.4626  1.3683
< cum.nF12          0.2412  0.7509   0.2023  0.5815
< cum.nF14         -0.2702 -0.6070  -0.3015 -0.6742
< cum.nF15         -0.2702 -0.6070  -0.3015 -0.6742
< cum.nF16         -0.2702 -0.6070  -0.3015 -0.6742
< cum.nF17         -0.2702 -0.6070  -0.3015 -0.6742
< cum.nF18         -0.2702 -0.6070  -0.3015 -0.6742
< cum.nF19         -0.2702 -0.6070  -0.3015 -0.6742
< cum.nF20          0.4472  1.6475   0.4472  1.4832
< cum.nF21         -0.2702 -0.6070  -0.3015 -0.6742
---
> date            -0.20870  0.29227 -0.11067 -0.30522
> t1               0.04567  0.79181  0.09821  0.28295
> t2               0.97773  2.30939  0.99409  2.46744
> cap              0.35439  0.91884  0.35682  0.89476
> ne              -0.21757 -0.14452 -0.16750 -0.43345
> ct              -0.33503 -0.58282 -0.31468 -0.81208
> bw               0.07756 -0.30877  0.04495  0.12022
> cum.nF1         -0.14217 -0.09243 -0.11006 -0.28376
> cum.nF2          0.00458  0.26097  0.03005  0.08049
> cum.nF3         -0.14217 -0.09243 -0.11006 -0.28376
> cum.nF5          0.18690  0.75094  0.20357  0.58153
> cum.nF6         -0.32089 -0.60698 -0.30790 -0.67420
> cum.nF7         -0.38788 -1.15087 -0.44620 -0.96922
> cum.nF8          0.56763  0.94599  0.46453  1.36832
> cum.nF11         0.56763  0.74536  0.46453  1.36832
> cum.nF12         0.18690  0.75094  0.20357  0.58153
> cum.nF14        -0.32089 -0.60698 -0.30790 -0.67420
> cum.nF15        -0.32089 -0.60698 -0.30790 -0.67420
> cum.nF16        -0.32089 -0.60698 -0.30790 -0.67420
> cum.nF17        -0.32089 -0.60698 -0.30790 -0.67420
> cum.nF18        -0.32089 -0.60698 -0.30790 -0.67420
> cum.nF19        -0.32089 -0.60698 -0.30790 -0.67420
> cum.nF20         0.44721  1.64751  0.44721  1.48324
> cum.nF21        -0.32089 -0.60698 -0.30790 -0.67420
221,239c221,239
< date              0.1001  0.2923  -0.1098 -0.3052
< t1                0.2154  0.7918   0.0976  0.2830
< t2                1.0226  2.3094   0.9861  2.4674
< cap               0.3587  0.9188   0.3525  0.8948
< ne               -0.0497 -0.1445  -0.1656 -0.4334
< ct               -0.2657 -0.5828  -0.3113 -0.8121
< bw               -0.0251 -0.3088   0.0445  0.1202
< cum.nF1          -0.0913 -0.0711  -0.2065 -0.2217
< cum.nF2           0.0498  0.2007  -0.0412  0.0629
< cum.nF3          -0.0913 -0.0711  -0.2065 -0.2217
< cum.nF5           0.2248  0.5776   0.1650  0.4543
< cum.nF6          -0.3062 -0.4669  -0.3536 -0.5267
< cum.nF8           0.1342  0.7667   0.4456  1.0690
< cum.nF11          0.1342  0.6211   0.4456  1.0690
< cum.nF12          0.2248  0.5776   0.1650  0.4543
< cum.nF14         -0.3062 -0.4669  -0.3536 -0.5267
< cum.nF15         -0.3062 -0.4669  -0.3536 -0.5267
< cum.nF16         -0.3062 -0.4669  -0.3536 -0.5267
< cum.nFNA         -0.4656 -1.0206  -0.4403 -1.0783
---
> date             -0.2087  0.2923  -0.1107 -0.3052
> t1                0.0457  0.7918   0.0982  0.2830
> t2                0.9777  2.3094   0.9941  2.4674
> cap               0.3544  0.9188   0.3568  0.8948
> ne               -0.2176 -0.1445  -0.1675 -0.4334
> ct               -0.3350 -0.5828  -0.3147 -0.8121
> bw                0.0776 -0.3088   0.0450  0.1202
> cum.nF1          -0.2406 -0.0711  -0.2100 -0.2217
> cum.nF2          -0.0658  0.2007  -0.0418  0.0629
> cum.nF3          -0.2406 -0.0711  -0.2100 -0.2217
> cum.nF5           0.1507  0.5776   0.1667  0.4543
> cum.nF6          -0.3759 -0.4669  -0.3639 -0.5267
> cum.nF8           0.5606  0.7667   0.4487  1.0690
> cum.nF11          0.5606  0.6211   0.4487  1.0690
> cum.nF12          0.1507  0.5776   0.1667  0.4543
> cum.nF14         -0.3759 -0.4669  -0.3639 -0.5267
> cum.nF15         -0.3759 -0.4669  -0.3639 -0.5267
> cum.nF16         -0.3759 -0.4669  -0.3639 -0.5267
> cum.nFNA         -0.4347 -1.0206  -0.4465 -1.0783
246,263c246,263
< date              0.1476  0.4662  -0.0986 -0.2602
< t1                0.2089  0.9554   0.2004  0.5520
< t2                0.9223  1.8952   0.9145  2.0968
< cap               0.4710  1.1309   0.4837  1.1324
< ne               -0.3254 -0.8303  -0.4882 -1.1088
< ct                0.0985  0.2868  -0.0833 -0.2041
< bw               -0.1900 -0.7283  -0.0625 -0.1529
< cum.nF1          -0.0913 -0.2378  -0.2065 -0.4900
< cum.nF2           0.0498  0.1332  -0.0412 -0.1005
< cum.nF3          -0.0913 -0.2378  -0.2065 -0.4900
< cum.nF5           0.2248  0.6341   0.1650  0.4214
< cum.nF6          -0.3062 -0.6547  -0.3536 -0.7500
< cum.nF8           0.1342  0.6623   0.4456  1.1558
< cum.nF11          0.1342  0.3333   0.4456  1.1558
< cum.nF12          0.2248  0.6341   0.1650  0.4214
< cum.nF14         -0.3062 -0.6547  -0.3536 -0.7500
< cum.nF15         -0.3062 -0.6547  -0.3536 -0.7500
< cum.nF16         -0.3062 -0.6547  -0.3536 -0.7500
---
> date             -0.1725  0.4662  -0.0994 -0.2602
> t1                0.1988  0.9554   0.2012  0.5520
> t2                0.9227  1.8952   0.9247  2.0968
> cap               0.4948  1.1309   0.4915  1.1324
> ne               -0.5423 -0.8303  -0.4977 -1.1088
> ct               -0.1343  0.2868  -0.0845 -0.2041
> bw               -0.0256 -0.7283  -0.0635 -0.1529
> cum.nF1          -0.2406 -0.2378  -0.2100 -0.4900
> cum.nF2          -0.0658  0.1332  -0.0418 -0.1005
> cum.nF3          -0.2406 -0.2378  -0.2100 -0.4900
> cum.nF5           0.1507  0.6341   0.1667  0.4214
> cum.nF6          -0.3759 -0.6547  -0.3639 -0.7500
> cum.nF8           0.5606  0.6623   0.4487  1.1558
> cum.nF11          0.5606  0.3333   0.4487  1.1558
> cum.nF12          0.1507  0.6341   0.1667  0.4214
> cum.nF14         -0.3759 -0.6547  -0.3639 -0.7500
> cum.nF15         -0.3759 -0.6547  -0.3639 -0.7500
> cum.nF16         -0.3759 -0.6547  -0.3639 -0.7500
 Running 'xBalanceTests2.R' [2s]
 Comparing 'xBalanceTests2.Rout' to 'xBalanceTests2.Rout.save' ... OK
** running tests for arch 'x64' ... ERROR
Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:

 > library(testthat)
 > library(RItools)
 Loading required package: SparseM

 Attaching package: 'SparseM'

 The following object is masked from 'package:base':

     backsolve

 >
 > test_check("RItools")

*CRASH*

Please fix and resubmit.

Best,
Uwe Ligges







On 06.05.2016 14:45, Jake Bowers wrote:
[This was generated from CRAN.R-project.org/submit.html]

The following package was uploaded to CRAN:
===========================================

Package Information:
Package: RItools
Version: 0.1-14
Title: Randomization Inference Tools
Author(s): Jake Bowers <jwbowers@illinois.edu>, Mark Fredrickson
 <mark.m.fredrickson@gmail.com>, and Ben Hansen
 <ben.hansen@umich.edu>
Maintainer: Jake Bowers <jwbowers@illinois.edu>
Depends: R (>= 2.2.0), SparseM
Suggests: testthat, roxygen2, MASS, RSVGTipsDevice
Description: Tools for randomization inference.
License: GPL (>=2)
Imports: grDevices, abind, xtable, svd, stats, graphics, methods,
 survival


The maintainer confirms that he or she
has read and agrees to the CRAN policies.

Submitter's comment: ## Resubmission
This version no longer includes
 cran-comments.md. It is now listed in
 .Rbuildignore

## Test environments
* local OS X
 install, R 3.3.0
* win-builder (devel and
 release)

## R CMD check results

Only error from
 lack of RSVGTipsDevice library on win-builder
 server.

## Downstream dependencies

We have also run
 R CMD check on downstream dependencies of RItools
 using `devtools::revdep_check()`



=================================================

Original content of DESCRIPTION file:

Package: RItools
Version: 0.1-14
Title: Randomization Inference Tools
Author: Jake Bowers <jwbowers@illinois.edu>, Mark Fredrickson
   <mark.m.fredrickson@gmail.com>, and Ben Hansen <ben.hansen@umich.edu>
Maintainer: Jake Bowers <jwbowers@illinois.edu>
Description: Tools for randomization inference.
License: GPL (>=2)
LazyData: true
Depends: R (>= 2.2.0), SparseM
Imports: grDevices, abind, xtable, svd, stats, graphics, methods,
       survival
Suggests: testthat, roxygen2, MASS, RSVGTipsDevice
Enhances: optmatch
URL: http://CRAN.R-project.org/package=RItools,
       http://www.jakebowers.org/ RItools.html
RoxygenNote: 5.0.1
NeedsCompilation: no
Packaged: 2016-05-06 12:30:06 UTC; jwbowers
```

**Comment by benthestatistician** [comment]
@jwbowers,  could you clarify which commit/branch it was you submitted?

**Comment by jwbowers** [comment]
master branch, commit  9b558a2   .

**Comment by benthestatistician** [comment]
I think we may have pushed up a bigger change than I thought we were pushing up. If memory serves, the last change we pushed was a bug fix of a prior snapshot of development, brought on by a request from Martin Maechler to fix something or the other.  Since then we, or at least I, have been using master without the premise that it was necessarily ready to push to CRAN. This material is in need of, at a minimum, some code review, if not also a merging in of the various other branches we've been working on, prior to pushing up to CRAN. 

Perhaps I should be using branches differently.  However, in the immediate term I think we should consider cherry-picking the minimal set of commits (since our last release) necessary to fix this latest problem. Perhaps those could go on a branch titled 0.1-15.  Thoughts?

**Comment by benthestatistician** [comment]
The just created issue71 branch starts off of master just prior to @josherrickson's merge of the clusters branch into master in mid-Februrary [master 07d25e7f].  The issue71 branch then cherry picks just a couple of more recent commits, including of course the one with which @josherrickson fixed #69.  

On my mac the result passes make check against R 3.2.3, with the only warning relating to me not having qpdf set up on my system.  Remains to be checked:

- [ ] against R 3.3;  
- [ ] on Windows,  w/ R 3.3 and new 64 bit gcc toolkit or whatever.  

To make it easy for somebody else to help w/ this if they're got access to either of these, I attach the tarball I made off the current HEAD of that branch, ie 309d66f1. 

When that passes:    
- [ ] make a release tag
- [ ] submit to CRAN. 
(@jwbowers, those release tags will be helpful for stuff like this moving forward -- it took me a bit to figure out where our last CRAN release was.)
[RItools_0.1-15.tar.gz](https://github.com/markmfredrickson/RItools/files/253539/RItools_0.1-15.tar.gz)

**Comment by benthestatistician** [comment]
PS: Before anybody else goes out of their way to set up the Windows test, I did just install the current Rtools/R on a Win7 VM that I've got.  So I can try that test if it's not convenient for anybody else -- just running out of time for that this afternoon.

**Comment by josherrickson** [comment]
I'm not sure that recent changes are to blame for the Windows issue. As Jake pointed out in #70, the windows build of 0.1-13 had the same non-informative crash on WIndows 64 (see here https://cran.rstudio.com/web/checks/check_results_RItools.html).

Hopefully your Windows 7 VM will expose this crash in a way we can test against it, because I don't believe we were seeing the issue using `build_win()`.

**Comment by benthestatistician** [comment]
Unfortunately I see the same thing: when it gets to `test_check("RItools")` it dies saying "no tests found for RItools".

**Comment by benthestatistician** [comment]
I should add that the problem is only with 64 bit R, the i386 version goes through just fine.  This is an odd problem. Hard to believe RItools is causing it, particularly given that it occurs only on one platform, really a half a platform (64 bit windows only).  I couldn't find anything about it on the forums, but I'm maybe not the best searcher.   Could somebody else try it? If we can't figure it out for ourselves then maybe we should ask the testthat people if they have any hints to offer?  

This tarball [RItools_0.1-15.tar.gz](https://github.com/markmfredrickson/RItools/files/254244/RItools_0.1-15.tar.gz) is a bit better to test from; the last one had been built just after a `make clean`, which has the side effect of removing ./man and thus bringing about additional check errors regarding missing documentation.

**Comment by josherrickson** [comment]
A few ideas of what to test (I don't have a Win 64 machine easily available):

- First, please confirm that `devtools::test()` works.
- Remove `library(testthat)` from the top of each `tests/testthat/test.*.R` file. I don't think this'll work because it seems like its never even seeing those files, but those lines aren't needed.
- It seems most likely to me that if another package is causing it, it's RSVGDeviceTips - remove that completely. You'll have to remove it from `DESCRIPTION` and chop it out of `R/plot.xbal.R` and `tests/testthat/test.plot.xbal.R`.
- Force a minimum version on `testthat`. In `DESCRIPTION`, use `testthat (>= 0.11.0),` (taken from optmatch).
- Add a copy of all `test.*.R` files to `inst/tests` (the old location they're supposed to live, this is related to the last suggestion). 
- Remove the word "Test" from the various filenames in `tests/*.R` e.g. `xBalanceTests.R`. Perhaps some grep is getting confused by them.

**Comment by benthestatistician** [comment]
On my Windows 7 virtual machine, I can confirm that `devtools::test()` works with 32-bit R but **not** with 64-bit R.  

I.e.,    

```{r}
> library(devtools)
> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.11.1

loaded via a namespace (and not attached):
[1] withr_1.0.1   memoise_1.0.0 digest_0.6.9 
> devtools::test()
Loading RItools
Loading required package: testthat
Testing RItools
Plotting Functions: ..
Utility Functions: ............
xBalance Functions: ..................................

DONE ===========================================================================

```

while on the other hand

```{r}
> library(devtools)
> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.11.1

loaded via a namespace (and not attached):
[1] withr_1.0.1   memoise_1.0.0 digest_0.6.9 
> devtools::test()
> Loading RItools
Loading required package: testthat
Testing RItools

```
...and then it crashes R.

Given this, which of the other tests should we report on in a devtools issue?  

Please also share thoughts on whether the issue should be posted to devtools or to testthat.

**Comment by josherrickson** [comment]
Does this work: `testthat::test_dir("tests/testthat")`? The tests will likely fail, but are they at least found?

If so, I think the error is in devtools (as that's the last call in [devtools/test.r](https://github.com/hadley/devtools/blob/master/R/test.r#L56)). If not, the error is in testthat in [testthat/test-files.R](https://github.com/hadley/testthat/blob/a102b89a8f23120ea5e614a1adf229b947e14850/R/test-files.R#L30) My guess is going to be on the devtools side.

If you're ambitious, you could try stepping through those functions to find exactly where things go sideways?

**Comment by benthestatistician** [comment]
1.  `testthat::test_dir("tests/testthat")` does work, in the sense of finding the tests and of not causing R as a whole to die.  so it seems we have traced the problem into `devtools`, as opposed to `testthat`. (Good thinking, @josherrickson !)
2. not feeling ambitious from here. Rather feeling anxious about this taking over from other priorities. Doess anyone disagree that we have enough information now to file a useful bug report for the devtools team?

**Comment by josherrickson** [comment]
I think we can file. We might also be able to craft our CRAN comments to re-submit by linking to the relevant issue. (We will have to address the diff issue, which just requires regenerating the .Rout.save files, assuming someone checks the new values for issue.)

**Comment by benthestatistician** [comment]
For various reasons, I wound up doing the step-through @josherrickson had suggested.

 `test_package` is the interactive-use alternative to `test_check`.  By running debug on this, I'm able to trace the issue to the call to `system.file` in that function.  

On my Mac I see. 
```{r}
R version 3.2.3 (2015-12-10) -- "Wooden Christmas-Tree"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.3.0 (64-bit)

<...>

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> system.file("tests", package="RItools")
[1] ""
> library(withr)
> with_libpaths("../RItools.Rcheck/", library(RItools), "pre")
> system.file("tests", package="RItools")
[1] "/Users/bbh/Documents/workingcopies/ritools/rel0.1-15/RItools.Rcheck/RItools/tests"
```
whereas from the Windows VM,
```{r}
R version 3.3.0 (2016-05-03) -- "Supposedly Educational"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)
<...>
Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> system.file("tests", "RItools")
[1] ""
> library(withr)
> with_libpaths("../RItools.Rcheck/", library(RItools), "pre")
> system.file("tests", "RItools")
[1] ""
```
I get the same thing with 32 bit R run from the same Win7 VM. In other words, `base:system.file()` is giving more accurate and informative answers on my Mac R than on the Windows R.  (In principle it's possible that this has to do with differnet versions of R, not different platforms: I'd appreciate it if somebody could confirm the Mac behavior I note above, but using R 3.3 not R 3.2.3.)

There are indications that the devtools team anticipated some quirkiness on the part of  `base:system.file()`.  On both 32 bit and 64 bit Windows setups, the call to `system.file` inside of `test_package` returns ` "C:/Users/bbh/R/win-library/3.3/RItools/tests"`, not "".  I think that's because it's the devtools people's special replacement version of `system.file`, not base R's `system.file`, that was used; and the devtools version is smarter. However, it's still giving the wrong answer.  Given the context it should have pointed to a subdirectory of "../RItools.Rcheck/", as it did on my Mac. In that location R finds an older 32 bit installation of RItools, but not a 64 bit one.  In 32 bit R, this results in the function's running the wrong tests, the ones for the older RItools installation; in 64 bit R, it crashes R.  

In summary, it appears that the cleverness behind the devtools people's replacement version of `system.file` isn't working in R 3.3.0 for windows.  Possibly because of them, possibly because of something to do with how the windows toolkit is installing packages, or possibly due to some quirk of our package.

As a next step, I propose to post something at the devtools repo. I'll wait at least a day to give time for comments first.

**Comment by josherrickson** [comment]
Trying to replicate on 3.3 on OS X, what did you run previous to generate the RItools.Rcheck folder? `Rcmd check` or something?

**Comment by benthestatistician** [comment]
Yes, I had run Rcmd check. The basic story ought to be replicable by
installing in any project-specific package library, however.

**Comment by josherrickson** [comment]
I get results more similar to the Windows run...

```
> library(withr)
> with_libpaths("../RItools.Rcheck/", library(RItools), "pre")
> system.file("tests", package="RItools")
[1] ""
> getwd()
[1] "/Users/josh/repositories/r/RItools.Rcheck"
> system.file("R", package="RItools")
[1] "/Users/josh/repositories/r/RItools.Rcheck/RItools/R"
> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.4 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] RItools_0.1-14  SparseM_1.7     withr_1.0.1     testthat_1.0.2
[5] devtools_1.11.1

loaded via a namespace (and not attached):
 [1] lattice_0.20-33 digest_0.6.9    crayon_1.3.1    grid_3.3.0
 [5] R6_2.1.2        xtable_1.8-2    magrittr_1.5    svd_0.4
 [9] Matrix_1.2-6    splines_3.3.0   abind_1.4-3     survival_2.39-3
[13] memoise_1.0.0
```

Additionally, my `tests` folder lives in `/RItools.Rcheck/tests` rather than `RItools.Rcheck/RItools/tests`.

**Comment by benthestatistician** [comment]
Thanks, @josherrickson .  I see now that I was working with an unclean RItools.Rcheck folder -- redoing it from scratch, I too have an `RItools.Rcheck/tests` but not an `RItools.Rcheck/RItools/tests`, and I get similar outputs as yours. Further the commands I reported on earlier weren't quite right -- `system.file("tests", "RItools")` is not synonymous with `system.file("tests", package="RItools")` -- so the OSX results I previously should be ignored.  (I'll have to loop back to thinking about what this changes, if anything.)

**Comment by benthestatistician** [comment]
Looking more closely at the structure of these testing functions, there may be a problem with devtools's `system.file` but it's not involved in the failing `Rcmd CHECK`.  While `test_check`'s interactive replacement (`test_package`) uses `system.file`, `test_check` itself uses a simpler mechanism, taking advantage of an assumption that `tests` is already the working directory.

```{r}
> test_check
function (package, filter = NULL, reporter = "check", ...) 
{
    library(testthat)
    require(package, character.only = TRUE)
    test_path <- "testthat"
    if (!utils::file_test("-d", test_path)) {
        stop("No tests found for ", package, call. = FALSE)
    }
    run_tests(package, test_path, filter, reporter, ...)
}
<environment: namespace:testthat>
```

To do: 

- step through this using R3.3 on Windows
- revisit issues of how to describe the problem & who to pass it to.

**Comment by benthestatistician** [comment]
None of that crap was the problem. The problem was caused by RSVGTipsDevice, which doesn't appear to be being actively maintained and isn't officially available on Windows on CRAN. It was being invoked in `tests/testthat/test.plot.xbal.R`, here:

```{r}
if(require(RSVGTipsDevice)) {
<...>
```
I guess the CRAN checker had a partly broken copy of the package installed anyway, so that it got past that `require` step. It causes the crash a few lines later, at `dev.off()`. 

In [issue71 13c75fe] I disable the test for windows.:
```{r}
 if(.Platform[['OS.type']]!='windows' && # #71
     require('RSVGTipsDevice') 
     ) {
<...>
```

 The result, attached, gets through `Rcmd.exe check` on both versions of windows, and gets through the `make check` on osx/R version 3.2.3.  
[RItools_0.1-15.tar.gz](https://github.com/markmfredrickson/RItools/files/267323/RItools_0.1-15.tar.gz)
. 

@jwbowers, in your court now.  When you do give it back to CRAN, could you create a release tag in github?

**Comment by josherrickson** [comment]
Ben, did you check that `plot.xbal` works on the various versions? At least not erroring, but hopefully being able to use RSVGTipsDevice if its installed? If there's any quirks, a note somewhere might be in order.

**Comment by benthestatistician** [comment]
Hey @josherrickson: 

1. I find that on Windows the rest of our tests for plot.xbal go through once we turn off the RSVGTipsDevice-specific tests.  
2. Per your suggest [issue71 48b294e] adds a note about no RSVGTipsDevice to the NEWS. If you had something different in mind, feel free to tweak. 

As of now think the RSVGTipsDevice material is a quite obscure use case. At some point I'd like to write a paper about the sensitivity analysis related material it's there to support, but that point won't be today, tomorrow or the next day, and by the time we  get there we may find there's a new project based on [svglite](https://github.com/hadley/svglite) that supports the tooltip functionality we want. 

BTW, @jwbowers - just to avoid slipups/ambiguities, what I think is now ready for release is what you'll find on the issue71 branch, not what's in master.

**Comment by benthestatistician** [comment]
There's not much left to do here, but I know that Jake is traveling with family, so it may be difficult for him to push it along.  @josherrickson, I think you've got an up-to-date R and development environment -- could you check the tarball I posted a couple comments back on this issue discussion thread?  (Or the HEAD of the issue71 branch, whichever you prefer.)

**Comment by josherrickson** [comment]
HEAD of issue71 passes all checks on my system. I added Travis support to the branch and ran on the windows build server, will update once those both finish running.

**Comment by josherrickson** [comment]
I'm getting a lot of errors on both those sources - at least several of which were addressed in master at some point. Given that we've tracked down the issue with with RSVGTipsDevice, is there any reason to use issue71 over master? Its much easier to merge that RSVGTipsDevice fix into master than the other way around.

**Comment by josherrickson** [comment]
Per offline discussion with Ben, issue71 branch has been updated with various fixes from Master. Issue71 branch now passes all checks & tests locally, via travis and via the winbuilder. Ready for release from my point of view.

**Comment by benthestatistician** [comment]
Thanks, @josherrickson.  I've confirmed that with your fixes I still get a clean bill of health from my two R-3.3.0 on Windows setups.   The one to-do that I can identify is to update the `cran-comments.md`, which in current form seems to refer to the January maintenance release. (Not sure of this file's role in the actual submission process, but even if we never give them a file called `cran-comments.md` it's useful to maintain a record of the comments we gave them with each submission.)  

As of this writing the cran-comments.md file includes the following:

>  ## R CMD check results
> 
> There was 1 NOTE with R stable and development from `devtools::build_win()`:
> 
> * checking package dependencies ... NOTE
>   Package suggested but not available for checking: 'RSVGTipsDevice'

I didn't see this when I checked it just now from my Windows setup.  Josh, did you see this when you checked it on win builder? It may have gone away at the same time that I fixed the bug that caused the error. If so, then we should excise this from the `cran-comments.md`.  

[issue71 6e01c31] adds my $.02 to cran-comments.md. At your convenience could you take a look at the current cran-comments.md, update as appropriate, then reassign this task to the package maintainer, ie Jake, for resubmission?

**Comment by josherrickson** [comment]
I saw no errors with RSVGTipsDevice on these recent runs. The cran comments seem fine to me. Reassigning to Jake.

**Comment by jwbowers** [comment]
Hi All. Running the devtools tests on issue71. Submitting issue71 branch to CRAN and will make a release of 0.1-15. Will close this issue when successful.

**Comment by jwbowers** [comment]
Submitted via `devtools::release()` at commit 07fca08
